# Autohor:NadineBestard
# Date 26/02/21

#Here I import the count matrices generated by CellRanger into R
#using Bioconductor packages. I will use the filtered matrices where an initial
#cellcalling has been done by CellRanger. In Cellranger version 5 the cellcalling
#is done with a very similar algorithm to dropletutilities one (ref).


# Set up ------
library(here)
library(DropletUtils)

# Create file path for each sample matrix and metadata ------
samples <- dir(here("data/filtered/"))
matrices <- here("data/filtered/", samples, "filtered_feature_bc_matrix")
metadata <- read_csv(here("data/metadata_scRNAseq.csv"))

# Create object -----
sce <- read10xCounts(matrices, samples, version = "auto", col.names = TRUE)
# add the metadata
coldata <- colData(sce)
coldata <- merge(x= coldata, y= metadata, by = "Sample", all.x=TRUE)
colData(sce) <- coldata
# Save the object
saveRDS(sce, here("processed", "sce.RDS"))


